project:
  type: book
  output-dir: _book

metadata-files: 
  - _lang-file.yml

execute: 
  cache: true
  freeze: auto

book:
  google-analytics: G-SLXFYRXJR4
  date: today
  date-format: iso 
  reader-mode: true
  search: true

  favicon: images/cover/book_fav.png
  repo-actions: [edit, issue]
  downloads: [pdf, epub]

bibliography: [biblio/book.bib, biblio/grateful-refs.bib]
biblio-style: apalike
csl: biblio/ecology.csl

format:
  html:
    from: markdown+emoji
#    number-depth: 2
 #   toc-depth: 3
    number-sections: true
    theme:
      light: cosmo #, css/theme.scss]
      dark: [cosmo, css/theme-dark.scss]
#    css: css/style.css
    code-link: true
    author-meta: "Julien Martin"

#    callout-appearance: simple

  pdf: 
    from: markdown+emoji
#    number-depth: 2
#    toc-depth: 2
    df-print: paged
    number-sections: true
    documentclass: scrreprt
    pdf-engine: lualatex
#    keep-tex: true
    classoption:
      - "chapterprefix=true"
      - "headings=big"
      - "twoside=semi"
    papersize: letter
    fontsize: 11pt
    geometry:
    - top=2cm
    - bottom=2cm
    - left=2cm
    - right=2cm
    - footskip=1cm
    block-headings: false
    colorlinks: true
    linestretch: 1.5
    template-partials:
      - latex/before-title.tex
      - latex/before-body.tex
#        - title.tex
#      - toc.tex


  epub:
    from: markdown+emoji
    dev: svglite
    stylesheet: css/epub.css
    toc: true
#    epub-cover-image: images/cover_introR.jpg

params:
   echo_sol: true
   longrun: false
   html_pdf: true