---
title: Book plan for "On the R way to hell"
author: Julien Martin
date: today
format:
  html: default
  docx: default
---


## Preface
[done]{.aside}

- [x] book explanation
- [X] author info
- [X] credits 

## Part I: Using R
[*nearly done*]{.aside}

1. [X] start ([done]{.underline})
    - [X] intro to working with R
1. [X] basics ([done]{.underline})
    - [X] R basic use
1. data ([need tidyverse section]{.underline})
    - [X] basic R loading and wrangling data
    - tidyverse intro
1. graphics ([need advanced ggplot use]{.underline})
    - [X] making basic plot
    - [X] ggplot basic
    - ggplot advanced
1. [x] programming ([maybe talk about writing a package]{.underline})
    - loop and conditions (exist)
    - making function (exist)
    - making package - maybe just add a reference to that (not done)
1. Writing report and reproducible science with R ([need new screenshoot]{.underline})
    - [X] intro to Rmarkdown from install to use
1. Using git and github with R ([need last read]{.underline})
    - [X] intro to using git and github with R

## Part II: Fundamentals of statistics

[*A lot of new stuffs but some will come from course notes in BIO4158*]{.aside}

1. Why doing stats 
    - prediction, inference, observation
1. Model building and selection 
    - talk about causality
1. Notion of experimental design 
    - define replication, continuous, fixed and random effects
1. Frequentist vs Bayesian
1. Distribution, CI and p-value
1. Permutation and Bootstrap
1. Multiple testing correction

## Part III: Linear models
[*A lot can be taken from the BIO4158 lab manual*]{.aside}

1. Principles and assumptions
1. Simple model
    - t-test
    - one-way anova
    - simple linear regression
1. Multiple model
    - multi-way anova
    - multiple regression
    - general linear regression

## Part IV: Generalized linear models
[*some from the Bio4158 and Bio8940 lab manual*]{.aside}

1. intro and principles
1. Count data
    - chi-square
    - poisson regression
1. Binary and proportion data
    - logistic regression

## Part V: Mixed models
[*A lot can be taken from the Bio8940 lab manual*]{.aside}

1. intro
1. LMM
1. GLMM
1. multivariate MM

## Part VI: Generalized additive models
[*Completely new*]{.aside}

1. intro to splines
1. gam

## Part VII: Multivariate analysis
[*Completely new*]{.aside}

1. PCA
1. Overview others

## Part VIII: Bayesian approach
[*A lot can be taken from the Bio8940 lab manual and WAM tutorial*]{.aside}

1. intro to Bayesian analysis
    - Bayes theorem
    - principle of parameter estimation with random walk
    - explanation of interpretation of posterior distribution
1. lm
    - redo and discuss some of lm/glm chapter cases using brms
1. lmm
    - redo and discuss some of lmm/glmm chapter cases using brms
1. gam
    - redo and discuss some of gam chapter cases using brms

## References 
[*done*]{.aside}

Code to automatically:

1. [X] cite all R packages
1. [X] create bibliography

## Appendices

1. Data files
    - list of data file used with link to download
1. Latex installation (done)
    - installation instruction for Quarto and latex